sudo: false
language: python
addons:
    apt:
        packages:
            - liblapack-dev
            - libatlas-dev
            - gfortran
install: 
    - pip install -r requirements.txt
    - python setup.py install
script: nosetests -v
